name: Terraform Deployment

on:
  workflow_call:
    inputs:
      region:
        description: "Region to deploy to"
        type: string
        required: true
        default: eu-west-1
      terraform-action:
        description: "Terraform Command"
        required: false
        type: string
        default: plan
      terraform-directory:
        description: "Directory in which to run Terraform"
        required: false
        type: string
        default: infra/terraform

permissions:
  id-token: write
  contents: read

jobs:
  TerraformPlan:
    runs-on: ubuntu-latest
    steps:
    - name: Git clone the repository
      uses: actions/checkout@v3
    - name: Install terraform
      uses: hashicorp/setup-terraform@v3
    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
        role-to-assume: arn:aws:iam::156041400744:role/github-ocid
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ inputs.region }}
    - name: Terraform Init
      run: |
        cd ${{ inputs.terraform-directory }}
        terraform init
    - name: Terraform Plan
      if: ${{ inputs.terraform-action == 'plan' }}
      run: |
        cd ${{ inputs.terraform-directory }}
        terraform plan
    - name: "Terraform apply"
      if: ${{ inputs.terraform-action == 'apply' }}
      shell: bash
      run: |
        cd ${{ inputs.terraform-directory }}
        terraform apply --auto-approve